### ISSUE TITLE
怎么停止？

### ISSUE THREAD

**Issue by hufenghuanyu** [wintercoder/BatchSaveWechatPicture#1]
有快捷键吗？我试了1000张，结果出了点问题，任务管理器没找到该程序，只好重启电脑了

**Comment by wintercoder** [comment]
运行期间任务管理器和系统右下角都有的，如果没了说明程序挂了

![image](https://user-images.githubusercontent.com/14596166/39800488-857e20f4-539a-11e8-8da3-c5e0db5dc6f2.png)

![image](https://user-images.githubusercontent.com/14596166/39800500-8cc28882-539a-11e8-820c-4e6e9bea269f.png)

数字不大的情况下 鼠标移走 等也可以

**Comment by hufenghuanyu** [comment]
搞定~！ 这个工具很好用哈 多谢

**Comment by jackylee1** [comment]
额，请问都保存到哪里了呢

**Comment by wintercoder** [comment]
> 额，请问都保存到哪里了呢

最开始按的时候，就有弹窗选择呀，你看readme的GIF
